package VT01;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class FramePrincipal extends javax.swing.JFrame {

    
    public String GeoID = new String();
    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelControles = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbMatrizX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tbMatrizY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tbZ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCor = new javax.swing.JComboBox<>();
        btnCriaGeo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxTransf = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tbDXAngulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tbDY = new javax.swing.JTextField();
        tbZoom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tbDeslocaX = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tbDeslocaY = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnTransforma = new javax.swing.JButton();
        btnAplicaDeslZoom = new javax.swing.JButton();
        jComboBoxGeo = new javax.swing.JComboBox<>();
        btnReset = new javax.swing.JButton();
        EntraArquivo = new javax.swing.JButton();
        jLabelTheta = new javax.swing.JLabel();
        jTextTheta = new javax.swing.JTextField();
        jLabelRho = new javax.swing.JLabel();
        jTextRho = new javax.swing.JTextField();
        jLabelPhi = new javax.swing.JLabel();
        jTextPhi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextD = new javax.swing.JTextField();
        jButtonVis = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextDZ = new javax.swing.JTextField();
        tbIdGeo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jCheckAnimar = new javax.swing.JCheckBox();
        jPanelDesenho = new PainelDesenho();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanelControles.setBorder(new javax.swing.border.MatteBorder(null));
        jPanelControles.setPreferredSize(new java.awt.Dimension(1000, 800));

        jLabel1.setText("X[] =");

        jLabel2.setText("Y[] =");

        jLabel3.setText("Z[] = ");

        jLabel4.setText("Cor:");

        jComboBoxCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RED", "BLUE", "GREEN", "BLACK", "GRAY", "ORANGE", "YELLOW", " " }));
        jComboBoxCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCorActionPerformed(evt);
            }
        });

        btnCriaGeo.setText("Criar Geometria");
        btnCriaGeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriaGeoActionPerformed(evt);
            }
        });

        jLabel5.setText("Geometria:");
        jLabel5.setToolTipText("");

        jComboBoxTransf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESCALA", "ROTAÇÃO", "TRANSLAÇÃO", " " }));
        jComboBoxTransf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTransfActionPerformed(evt);
            }
        });

        jLabel6.setText("Transform:");

        jLabel7.setText("DX / angulo:");

        jLabel8.setText("DY:");

        jLabel9.setText("Zoom:");
        jLabel9.setToolTipText("");

        jLabel10.setText("DxCenter:");
        jLabel10.setToolTipText("");

        jLabel11.setText("DyCenter:");
        jLabel11.setToolTipText("");

        btnTransforma.setText("Aplicar Transformação");
        btnTransforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransformaActionPerformed(evt);
            }
        });

        btnAplicaDeslZoom.setText("Aplicar Deslocamento e/ou Zoom");
        btnAplicaDeslZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicaDeslZoomActionPerformed(evt);
            }
        });

        btnReset.setText("Reset Deslocamento");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        EntraArquivo.setText("Ent. Arq.");
        EntraArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntraArquivoActionPerformed(evt);
            }
        });

        jLabelTheta.setText("Theta:");

        jLabelRho.setText("Rho:");

        jLabelPhi.setText("Phi:");

        jLabel12.setText("d:");

        jButtonVis.setText("Aplica Mod. Vis.");
        jButtonVis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisActionPerformed(evt);
            }
        });

        jLabel13.setText("DZ:");

        jLabel14.setText("ID =");

        jCheckAnimar.setText("Animar");
        jCheckAnimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckAnimarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelControlesLayout = new javax.swing.GroupLayout(jPanelControles);
        jPanelControles.setLayout(jPanelControlesLayout);
        jPanelControlesLayout.setHorizontalGroup(
            jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTheta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextTheta, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabelRho)
                .addGap(18, 18, 18)
                .addComponent(jTextRho, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextD, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelControlesLayout.createSequentialGroup()
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlesLayout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabelPhi)
                        .addGap(20, 20, 20)
                        .addComponent(jTextPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))
                    .addGroup(jPanelControlesLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelControlesLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbMatrizX, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelControlesLayout.createSequentialGroup()
                                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelControlesLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnCriaGeo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tbZ)
                                        .addComponent(jComboBoxCor, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tbMatrizY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelControlesLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbIdGeo)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelControlesLayout.createSequentialGroup()
                                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBoxTransf, javax.swing.GroupLayout.Alignment.LEADING, 0, 228, Short.MAX_VALUE)
                                    .addComponent(tbDXAngulo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxGeo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelControlesLayout.createSequentialGroup()
                                        .addComponent(tbDY, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextDZ, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlesLayout.createSequentialGroup()
                                .addComponent(btnTransforma, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)))))
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlesLayout.createSequentialGroup()
                        .addComponent(jButtonVis, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(EntraArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(95, 95, 95))
                    .addGroup(jPanelControlesLayout.createSequentialGroup()
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbDeslocaX, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbZoom, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbDeslocaY, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelControlesLayout.createSequentialGroup()
                                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCheckAnimar)
                                    .addComponent(btnAplicaDeslZoom, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelControlesLayout.setVerticalGroup(
            jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlesLayout.createSequentialGroup()
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tbMatrizX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxGeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6)
                                .addComponent(jComboBoxTransf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tbMatrizY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7)
                                .addComponent(tbDXAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tbZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelControlesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(tbIdGeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jComboBoxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAplicaDeslZoom)
                                    .addComponent(btnReset))
                                .addGap(12, 12, 12)
                                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCriaGeo)
                                    .addComponent(jCheckAnimar)))
                            .addGroup(jPanelControlesLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(tbDY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jTextDZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTransforma))))
                    .addGroup(jPanelControlesLayout.createSequentialGroup()
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(tbZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tbDeslocaX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tbDeslocaY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTheta)
                        .addComponent(jTextTheta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelRho)
                        .addComponent(jTextRho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jTextD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelPhi))
                    .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonVis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EntraArquivo)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanelDesenho.setBackground(new java.awt.Color(204, 51, 0));
        jPanelDesenho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanelDesenhoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDesenhoLayout = new javax.swing.GroupLayout(jPanelDesenho);
        jPanelDesenho.setLayout(jPanelDesenhoLayout);
        jPanelDesenhoLayout.setHorizontalGroup(
            jPanelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanelDesenhoLayout.setVerticalGroup(
            jPanelDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDesenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelControles, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelControles, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDesenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCorActionPerformed

    private void jComboBoxTransfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTransfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTransfActionPerformed

    private void btnCriaGeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriaGeoActionPerformed
        PegaPonto();
        SetComboBoxGeo();
    }//GEN-LAST:event_btnCriaGeoActionPerformed

    private void jPanelDesenhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanelDesenhoKeyPressed

    }//GEN-LAST:event_jPanelDesenhoKeyPressed

    private void btnTransformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransformaActionPerformed
        PegaTransformação();
    }//GEN-LAST:event_btnTransformaActionPerformed

    private void btnAplicaDeslZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicaDeslZoomActionPerformed
        PegaDeslocamento();
    }//GEN-LAST:event_btnAplicaDeslZoomActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        SetComboBoxGeo();
    }//GEN-LAST:event_formWindowActivated

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       ResetPadroes();
    }//GEN-LAST:event_btnResetActionPerformed

    private void EntraArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntraArquivoActionPerformed
        try {
            LeArquivo();
        } catch (IOException ex) {
            Logger.getLogger(FramePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EntraArquivoActionPerformed

    private void jButtonVisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisActionPerformed
        Transform3d();
    }//GEN-LAST:event_jButtonVisActionPerformed

    private void jCheckAnimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckAnimarActionPerformed
        if(jCheckAnimar.isSelected() == true)
        {
                jPanelDesenho.animar();
        }else
            jPanelDesenho.desanimar();
    }//GEN-LAST:event_jCheckAnimarActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.Exception
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EntraArquivo;
    private javax.swing.JButton btnAplicaDeslZoom;
    private javax.swing.JButton btnCriaGeo;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTransforma;
    private javax.swing.JButton jButtonVis;
    private javax.swing.JCheckBox jCheckAnimar;
    private javax.swing.JComboBox<String> jComboBoxCor;
    private javax.swing.JComboBox<String> jComboBoxGeo;
    private javax.swing.JComboBox<String> jComboBoxTransf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPhi;
    private javax.swing.JLabel jLabelRho;
    private javax.swing.JLabel jLabelTheta;
    private javax.swing.JPanel jPanelControles;
    public PainelDesenho jPanelDesenho;
    private javax.swing.JTextField jTextD;
    private javax.swing.JTextField jTextDZ;
    private javax.swing.JTextField jTextPhi;
    private javax.swing.JTextField jTextRho;
    private javax.swing.JTextField jTextTheta;
    private javax.swing.JTextField tbDXAngulo;
    private javax.swing.JTextField tbDY;
    private javax.swing.JTextField tbDeslocaX;
    private javax.swing.JTextField tbDeslocaY;
    private javax.swing.JTextField tbIdGeo;
    private javax.swing.JTextField tbMatrizX;
    private javax.swing.JTextField tbMatrizY;
    private javax.swing.JTextField tbZ;
    private javax.swing.JTextField tbZoom;
    // End of variables declaration//GEN-END:variables

    private void PegaPonto() {
        Geometria g = new Geometria();
        int ini = -1;
        int fim = -1;
        String Tx = tbMatrizX.getText();
        String Ty = tbMatrizY.getText();
        String Tz = tbZ.getText();
        String[] arrayX = Tx.split(";");
        String[] arrayY = Ty.split(";");
        String[] arrayZ = Tz.split(";");
        
        for (int i = 0; i < arrayX.length; i++) {
            float x = Float.parseFloat(arrayX[i]);
            float y = Float.parseFloat(arrayY[i]);
            float z = Float.parseFloat(arrayZ[i]);
            //g.getPontos().add(new Point2D(x, y));

            if (ini != -1 && fim == -1) {
                fim = i;
                g.getArestas().add(new Aresta(ini, fim));

                ini = -1;
                fim = -1;
            }
            if (ini == -1) {
                ini = i;
            }
        }

        String Id = tbIdGeo.getText();
        g.setId(Id);

        String cor = jComboBoxCor.getSelectedItem().toString();
        Color corSel = DescobreCor(cor);

        g.cor = corSel;
        jPanelDesenho.geometrias.add(g);
        jPanelDesenho.repaint();
        
    }

    public void PegaTransformação() {
        GeoID = DescobreGeometria();
        Geometria selecionada = jPanelDesenho.GetByNome(GeoID);
        String Transformacao = jComboBoxTransf.getSelectedItem().toString();
        float Graus;
        float DX;
        float DY;
        float DZ;

        if (Transformacao.equals("ROTAÇÃO") && tbDY.getText().isEmpty()) {
            Graus = Float.parseFloat(tbDXAngulo.getText());
            
            //jPanelDesenho.aplicaTransformacao(selecionada,-10, -20);
            jPanelDesenho.aplicaRotacao(Graus, selecionada);
           // jPanelDesenho.aplicaTransformacao(selecionada,10, 20);
            
        } else if (Transformacao.equals("TRANSLAÇÃO")) {
            if (tbDY.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Para translação o campo DY deve ser preenchido.");
            } else {
                DX = Float.parseFloat(tbDXAngulo.getText());
                DY = Float.parseFloat(tbDY.getText());
                DZ = Float.parseFloat(jTextDZ.getText());
                jPanelDesenho.aplicaTransformacao(selecionada, DX, DY, DZ);
            }
        } else if (Transformacao.equals("ESCALA")) {
            if (tbDY.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Para escala o campo DY deve ser preenchido.");
            } else {
                DX = Float.parseFloat(tbDXAngulo.getText());
                DY = Float.parseFloat(tbDY.getText());
                DZ = Float.parseFloat(jTextDZ.getText());
                jPanelDesenho.aplicaEscala(selecionada, DX, DY, DZ);
            }
        } else if (Transformacao.equals("ROTAÇÃO") && !tbDY.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Para rotação o campo DY deve ser apagado.");
        }
    }

    private void PegaDeslocamento() {

        if(tbDeslocaX.getText().isEmpty() || tbDeslocaY.getText().isEmpty())
        {
            float zoom = Float.parseFloat(tbZoom.getText());
            jPanelDesenho.setZoom(zoom);
        }else if(tbZoom.getText().isEmpty())
        {
            int deslocamentoX  = Integer.parseInt(tbDeslocaX.getText());
            int deslocamentoY = Integer.parseInt(tbDeslocaY.getText());
            jPanelDesenho.centerX = jPanelDesenho.centerX + deslocamentoX;
            jPanelDesenho.centerY = jPanelDesenho.centerY + deslocamentoY;
        }else 
        {
            float zoom = Float.parseFloat(tbZoom.getText());
            jPanelDesenho.setZoom(zoom);
            int deslocamentoX  = Integer.parseInt(tbDeslocaX.getText());
            int deslocamentoY = Integer.parseInt(tbDeslocaY.getText());
            jPanelDesenho.centerX = jPanelDesenho.centerX + deslocamentoX;
            jPanelDesenho.centerY = jPanelDesenho.centerY + deslocamentoY;
        }
        repaint();
    }

    private Color DescobreCor(String cor) {
        Color corS = null;
        if (cor.equals("BLUE")) {
            corS = Color.BLUE;
        }
        if (cor.equals("RED")) {
            corS = Color.RED;
        }
        if (cor.equals("BLACK")) {
            corS = Color.BLACK;
        }
        if (cor.equals("GREEN")) {
            corS = Color.GREEN;
        }
        if (cor.equals("GRAY")) {
            corS = Color.GRAY;
        }
        if (cor.equals("ORANGE")) {
            corS = Color.ORANGE;
        }
        if (cor.equals("YELLOW")) {
            corS = Color.YELLOW;
        }
        return corS;
    }

    private void ResetPadroes() {
        jPanelDesenho.centerX = jPanelDesenho.maxX / 2;
        jPanelDesenho.centerY = jPanelDesenho.maxY / 2;
        repaint();
    }

    private void SetComboBoxGeo() {
        String[] gArray = new String[jPanelDesenho.geometrias.size()];
        for (int i = 0; i < gArray.length; i++) {
            gArray[i] = jPanelDesenho.geometrias.get(i).getId();
        }
        jComboBoxGeo.setModel(new DefaultComboBoxModel<>(gArray));
        //jComboBoxGeo.setSelectedIndex(1);
    }

    private void LeArquivo() throws FileNotFoundException, IOException {
        
        String fileName = "C:\\Users\\felip\\OneDrive\\Documentos\\NetBeansProjects\\VT02_Malopes_\\src\\VT01\\cubo.data";
	BufferedReader reader = new BufferedReader(new FileReader(new File(fileName)));
        Geometria geometria = Geometria.build(reader);
        geometria.cor = Color.blue;
        jPanelDesenho.geometrias.add(geometria);
        repaint();
        SetComboBoxGeo();
   }

        private void Transform3d() {
        float theta;
        float phi;
        float rho;
        float d;
                
        theta = Float.parseFloat(jTextTheta.getText());
        phi = Float.parseFloat(jTextPhi.getText());
        rho = Float.parseFloat(jTextRho.getText());
        d = Float.parseFloat(jTextD.getText());
        
        jPanelDesenho.AplicaVisualizacao(theta, phi, rho,d);
    }

    private String DescobreGeometria() {
        String Geo = new String();
        Geo = jComboBoxGeo.getSelectedItem().toString();
        return Geo;
    }

}
